// Generated by scripts/build-locale-catalog.mjs. Do not edit manually.
export const defaultLocale = "zh-CN" as const;

export const localeCatalog = {
  "en-US": {
    "nativeName": "English",
    "oauthCallback": {
      "success": {
        "title": "Nami Mail authorization complete",
        "message": "Authorization is complete. You can close this window and return to Nami Mail."
      },
      "failure": {
        "title": "Nami Mail authorization not completed",
        "message": "Authorization was not completed. Return to Nami Mail to review the issue and try again."
      }
    }
  },
  "zh-CN": {
    "nativeName": "简体中文",
    "oauthCallback": {
      "success": {
        "title": "Nami Mail 授权完成",
        "message": "授权已完成，可以关闭此窗口并返回 Nami Mail。"
      },
      "failure": {
        "title": "Nami Mail 授权未完成",
        "message": "授权未完成，请返回 Nami Mail 查看原因并重试。"
      }
    }
  }
} as const;

export type SupportedLocale = keyof typeof localeCatalog;
