import type { Account, Message, OutboundSubmission, ProviderInfo, Stats } from "./types";
import { demoProviderCatalog } from "./demoProviderCatalog";

export const demoProviders: ProviderInfo[] = demoProviderCatalog;
export const demoAccounts: Account[] = [
  {
    id: "personal",
    email: "hello@icloud.com",
    provider: "icloud",
    providerName: "iCloud Mail",
    status: "connected",
    lastError: null,
    lastSyncedAt: new Date().toISOString(),
    signature: "——\n林晓\nNami Studio · 设计师",
    createdAt: new Date().toISOString(),
    folders: [
      { path: "INBOX", name: "收件箱", specialUse: "\\Inbox", total: 4, unseen: 3 },
      { path: "Archive", name: "归档", specialUse: "\\Archive", total: 0, unseen: 0 },
      { path: "Junk", name: "垃圾邮件", specialUse: "\\Junk", total: 0, unseen: 0 },
      { path: "Sent Messages", name: "已发送", specialUse: "\\Sent", total: 0, unseen: 0 },
      { path: "Drafts", name: "草稿", specialUse: "\\Drafts", total: 0, unseen: 0 },
    ],
  },
  {
    id: "work",
    email: "studio@gmail.com",
    provider: "gmail",
    providerName: "Gmail",
    status: "connected",
    lastError: null,
    lastSyncedAt: new Date(Date.now() - 62_000).toISOString(),
    signature: "",
    createdAt: new Date().toISOString(),
    folders: [
      { path: "INBOX", name: "收件箱", specialUse: "\\Inbox", total: 7, unseen: 0 },
      { path: "[Gmail]/All Mail", name: "所有邮件", specialUse: "\\All", total: 0, unseen: 0 },
    ],
  },
];

const now = Date.now();
export const demoSubmissions: OutboundSubmission[] = [
  {
    id: "demo-submission-unknown",
    accountId: "work",
    messageId: "<demo-unknown-7f31c52a@mailer.example>",
    subject: "合作提案最终确认",
    recipients: ["reviewer@example.com", "ops@example.test", "legal@example.test", "archive@example.com"],
    deliveryStatus: "unknown_delivery",
    sendAt: null,
    errorCode: "connection_failed",
    errorMessage: "发送连接在等待最终响应时中断，服务端是否接受邮件暂时无法确认。",
    postSubmitWarning: null,
    submittedAt: null,
    confirmedAt: null,
    createdAt: new Date(now - 17 * 60_000).toISOString(),
    updatedAt: new Date(now - 16 * 60_000).toISOString(),
  },
  {
    id: "demo-submission-submitting",
    accountId: "personal",
    messageId: "<demo-submitting-3ae8901b@mailer.example>",
    subject: "周末行程与预订信息",
    recipients: ["friend@example.com"],
    deliveryStatus: "submitting",
    sendAt: null,
    errorCode: null,
    errorMessage: null,
    postSubmitWarning: null,
    submittedAt: null,
    confirmedAt: null,
    createdAt: new Date(now - 42_000).toISOString(),
    updatedAt: new Date(now - 18_000).toISOString(),
  },
  {
    id: "demo-submission-confirmed",
    accountId: "personal",
    messageId: "<demo-confirmed-91d2bc40@mailer.example>",
    subject: "照片下载链接",
    recipients: ["studio@example.com", "editor@example.test"],
    deliveryStatus: "confirmed",
    sendAt: null,
    errorCode: null,
    errorMessage: null,
    postSubmitWarning: null,
    submittedAt: new Date(now - 3 * 60 * 60_000).toISOString(),
    confirmedAt: new Date(now - 2.9 * 60 * 60_000).toISOString(),
    createdAt: new Date(now - 3 * 60 * 60_000).toISOString(),
    updatedAt: new Date(now - 2.9 * 60 * 60_000).toISOString(),
  },
];

export const demoMessages: Message[] = [
  {
    id: "m1",
    accountId: "personal",
    accountEmail: "hello@icloud.com",
    providerName: "iCloud Mail",
    mailbox: "INBOX",
    uid: 101,
    subject: "周末，在安静的地方见",
    from: { name: "林澈", address: "lin@example.com" },
    to: [{ name: "You", address: "hello@icloud.com" }],
    cc: [],
    sentAt: new Date(now - 12 * 60_000).toISOString(),
    snippet: "找到一家很安静的新店。窗边的位置下午有很好的光，我们周六四点见？",
    textBody: "找到一家很安静的新店。\n\n窗边的位置下午有很好的光，我们周六四点见？\n\n林澈",
    htmlBody: "",
    flags: [],
    seen: false,
    flagged: false,
    hasAttachments: false,
    attachments: [],
    size: 1832,
  },
  {
    id: "m2",
    accountId: "work",
    accountEmail: "studio@gmail.com",
    providerName: "Gmail",
    mailbox: "INBOX",
    uid: 202,
    subject: "Design review · July notes",
    from: { name: "Mira Studio", address: "notes@mira.studio" },
    to: [{ name: "Studio", address: "studio@gmail.com" }],
    cc: [],
    sentAt: new Date(now - 48 * 60_000).toISOString(),
    snippet: "The quieter navigation direction feels right. We kept the hierarchy and removed three competing accents.",
    textBody: "The quieter navigation direction feels right.\n\nWe kept the hierarchy and removed three competing accents. The prototype is ready for a final pass tomorrow morning.\n\n— Mira",
    htmlBody: "",
    flags: ["\\Seen", "\\Flagged"],
    seen: true,
    flagged: true,
    hasAttachments: true,
    attachments: [{ partId: "2", filename: "july-review-notes.pdf", contentType: "application/pdf", size: 24124, related: false, disposition: "attachment" }],
    size: 24124,
  },
  {
    id: "m3",
    accountId: "personal",
    accountEmail: "hello@icloud.com",
    providerName: "iCloud Mail",
    mailbox: "INBOX",
    uid: 102,
    subject: "你的七月账单已就绪",
    from: { name: "North Bank", address: "hello@northbank.example" },
    to: [{ name: "You", address: "hello@icloud.com" }],
    cc: [],
    sentAt: new Date(now - 4 * 60 * 60_000).toISOString(),
    snippet: "本月账单已经生成。相比上月，你的订阅支出减少了 18%。",
    textBody: "本月账单已经生成。相比上月，你的订阅支出减少了 18%。\n\n登录官方客户端可查看明细。",
    htmlBody: "",
    flags: [],
    seen: false,
    flagged: false,
    hasAttachments: false,
    attachments: [],
    size: 4240,
  },
  {
    id: "m4",
    accountId: "work",
    accountEmail: "studio@gmail.com",
    providerName: "Gmail",
    mailbox: "INBOX",
    uid: 203,
    subject: "Re: launch checklist",
    from: { name: "Noah", address: "noah@atelier.example" },
    to: [{ name: "Studio", address: "studio@gmail.com" }],
    cc: [],
    messageId: "<launch-reply@atelier.example>",
    inReplyTo: "<launch-checklist@atelier.example>",
    references: ["<launch-checklist@atelier.example>"],
    sentAt: new Date(now - 24 * 60 * 60_000).toISOString(),
    snippet: "Everything on my side is signed off. I left one small note on the mobile transition.",
    textBody: "Everything on my side is signed off. I left one small note on the mobile transition.\n\nNo rush — tomorrow is perfect.",
    htmlBody: "",
    flags: ["\\Seen"],
    seen: true,
    flagged: false,
    hasAttachments: false,
    attachments: [],
    size: 2860,
  },
  {
    id: "m5",
    accountId: "personal",
    accountEmail: "hello@icloud.com",
    providerName: "iCloud Mail",
    mailbox: "INBOX",
    uid: 103,
    subject: "照片整理好了",
    from: { name: "陈屿", address: "yu@example.com" },
    to: [{ name: "You", address: "hello@icloud.com" }],
    cc: [],
    sentAt: new Date(now - 2 * 24 * 60 * 60_000).toISOString(),
    snippet: "上周拍的照片我挑了二十张，原片和调色版本都放在附件里。",
    textBody: "上周拍的照片我挑了二十张，原片和调色版本都放在附件里。\n\n喜欢第三组的光线。",
    htmlBody: "",
    flags: ["\\Seen"],
    seen: true,
    flagged: false,
    hasAttachments: true,
    attachments: [{ partId: "2", filename: "weekend-photos.zip", contentType: "application/zip", size: 8842, related: false, disposition: "attachment" }],
    size: 8842,
  },
  {
    id: "m6",
    accountId: "work",
    accountEmail: "studio@gmail.com",
    providerName: "Gmail",
    mailbox: "INBOX",
    uid: 204,
    subject: "launch checklist",
    from: { name: "Mira Studio", address: "notes@mira.studio" },
    to: [{ name: "Studio", address: "studio@gmail.com" }],
    cc: [],
    messageId: "<launch-checklist@atelier.example>",
    sentAt: new Date(now - 30 * 60 * 60_000).toISOString(),
    snippet: "Final checklist before we ship on Friday. Design sign-off, copy pass, and the mobile transition note.",
    textBody: "Final checklist before we ship on Friday:\n\n- Design sign-off\n- Copy pass\n- Mobile transition note\n\nPlease confirm each item today.",
    htmlBody: "",
    flags: ["\\Seen"],
    seen: true,
    flagged: false,
    hasAttachments: false,
    attachments: [],
    size: 3240,
  },
  {
    id: "m8",
    accountId: "work",
    accountEmail: "studio@gmail.com",
    providerName: "Gmail",
    mailbox: "INBOX",
    uid: 205,
    subject: "Re: launch checklist",
    from: { name: "Mira Studio", address: "notes@mira.studio" },
    to: [{ name: "Studio", address: "studio@gmail.com" }],
    cc: [],
    messageId: "<launch-check-205@atelier.example>",
    inReplyTo: "<launch-checklist@atelier.example>",
    references: ["<launch-checklist@atelier.example>"],
    sentAt: new Date(now - 29 * 60 * 60_000).toISOString(),
    snippet: "Design sign-off is done. The final pass over the illustration set landed this morning.",
    textBody: "Design sign-off is done. The final pass over the illustration set landed this morning.\n\nReady for the copy pass.",
    htmlBody: "",
    flags: ["\\Seen"],
    seen: true,
    flagged: false,
    hasAttachments: false,
    attachments: [],
    size: 2410,
  },
  {
    id: "m9",
    accountId: "work",
    accountEmail: "studio@gmail.com",
    providerName: "Gmail",
    mailbox: "INBOX",
    uid: 206,
    subject: "Re: launch checklist",
    from: { name: "Noah", address: "noah@atelier.example" },
    to: [{ name: "Studio", address: "studio@gmail.com" }],
    cc: [],
    messageId: "<launch-check-206@atelier.example>",
    inReplyTo: "<launch-checklist@atelier.example>",
    references: ["<launch-checklist@atelier.example>"],
    sentAt: new Date(now - 28 * 60 * 60_000).toISOString(),
    snippet: "Copy pass finished — button labels, empty states, and the onboarding screen are all consistent.",
    textBody: "Copy pass finished — button labels, empty states, and the onboarding screen are all consistent.\n\nTwo strings still need localization review.",
    htmlBody: "",
    flags: ["\\Seen"],
    seen: true,
    flagged: false,
    hasAttachments: false,
    attachments: [],
    size: 2540,
  },
  {
    id: "m10",
    accountId: "work",
    accountEmail: "studio@gmail.com",
    providerName: "Gmail",
    mailbox: "INBOX",
    uid: 207,
    subject: "Re: launch checklist",
    from: { name: "Mira Studio", address: "notes@mira.studio" },
    to: [{ name: "Studio", address: "studio@gmail.com" }],
    cc: [],
    messageId: "<launch-check-207@atelier.example>",
    inReplyTo: "<launch-checklist@atelier.example>",
    references: ["<launch-checklist@atelier.example>"],
    sentAt: new Date(now - 27 * 60 * 60_000).toISOString(),
    snippet: "The mobile transition note from the review is fixed — it now tracks the same easing as the desktop build.",
    textBody: "The mobile transition note from the review is fixed — it now tracks the same easing as the desktop build.\n\nBoth platforms animate consistently.",
    htmlBody: "",
    flags: ["\\Seen"],
    seen: true,
    flagged: false,
    hasAttachments: false,
    attachments: [],
    size: 2310,
  },
  {
    id: "m11",
    accountId: "work",
    accountEmail: "studio@gmail.com",
    providerName: "Gmail",
    mailbox: "INBOX",
    uid: 208,
    subject: "Re: launch checklist",
    from: { name: "Noah", address: "noah@atelier.example" },
    to: [{ name: "Studio", address: "studio@gmail.com" }],
    cc: [],
    messageId: "<launch-check-208@atelier.example>",
    inReplyTo: "<launch-checklist@atelier.example>",
    references: ["<launch-checklist@atelier.example>"],
    sentAt: new Date(now - 26 * 60 * 60_000).toISOString(),
    snippet: "Preparing the release build now. Everything on the list is checked, so we are good to ship on Friday.",
    textBody: "Preparing the release build now. Everything on the list is checked, so we are good to ship on Friday.\n\nOne last smoke test of the installer, then it is official.",
    htmlBody: "",
    flags: ["\\Seen"],
    seen: true,
    flagged: false,
    hasAttachments: false,
    attachments: [],
    size: 2470,
  },
  {
    id: "m7",
    accountId: "personal",
    accountEmail: "hello@icloud.com",
    providerName: "iCloud Mail",
    mailbox: "INBOX",
    uid: 104,
    subject: "【North Bank】登录验证码",
    from: { name: "North Bank", address: "security@northbank.example" },
    to: [{ name: "You", address: "hello@icloud.com" }],
    cc: [],
    messageId: "<demo-otp-91d0f7a2@northbank.example>",
    sentAt: new Date(now - 5 * 60_000).toISOString(),
    snippet: "你的 North Bank 账户登录验证码：483926，5 分钟内有效。",
    textBody: "你的 North Bank 账户登录验证码：483926\n\n该验证码 5 分钟内有效，请勿转发给任何人。如果你没有发起登录，可以忽略这封邮件。",
    htmlBody: "",
    flags: [],
    seen: false,
    flagged: false,
    hasAttachments: false,
    attachments: [],
    size: 1988,
  },
];

const demoTranslatedBodies: Record<string, { detectedLanguage: string; zh: string; en: string }> = {
  m1: {
    detectedLanguage: "zh",
    zh: "找到一家很安静的新店。\n\n窗边的位置下午有很好的光，我们周六四点见？\n\n林澈",
    en: "I found a lovely new quiet place.\n\nThe window seats have beautiful light in the afternoon. Shall we meet at four on Saturday?\n\nLin Che",
  },
  m2: {
    detectedLanguage: "en",
    zh: "更安静的导航方向感觉很对。\n\n我们保留了信息层级，并移除了三处相互竞争的视觉强调。原型已准备好，明天上午可以进行最后一轮检查。\n\n— Mira",
    en: "The quieter navigation direction feels right.\n\nWe kept the hierarchy and removed three competing accents. The prototype is ready for a final pass tomorrow morning.\n\n— Mira",
  },
  m3: {
    detectedLanguage: "zh",
    zh: "本月账单已经生成。相比上月，你的订阅支出减少了 18%。\n\n登录官方客户端可查看明细。",
    en: "Your July statement is ready. Compared with last month, your subscription spending is down 18%.\n\nSign in to the official app to view the details.",
  },
  m4: {
    detectedLanguage: "en",
    zh: "我这边都已确认。我在移动端过渡部分留了一条小建议。\n\n不用着急，明天处理正合适。",
    en: "Everything on my side is signed off. I left one small note on the mobile transition.\n\nNo rush — tomorrow is perfect.",
  },
  m5: {
    detectedLanguage: "zh",
    zh: "上周拍的照片我挑了二十张，原片和调色版本都放在附件里。\n\n喜欢第三组的光线。",
    en: "I sorted the photos from last week and picked twenty. The originals and color-graded versions are in the attachment.\n\nI like the light in the third set.",
  },
  m7: {
    detectedLanguage: "zh",
    zh: "你的 North Bank 账户登录验证码：483926\n\n该验证码 5 分钟内有效，请勿转发给任何人。如果你没有发起登录，可以忽略这封邮件。",
    en: "Your North Bank sign-in code: 483926\n\nThis code expires in 5 minutes. Never forward it to anyone. If you did not attempt to sign in, you can ignore this message.",
  },
};

/** Returns deterministic demo copy so demo mode never submits mail content to a network service. */
export function demoMessageTranslation(message: Message, targetLocale: string): {
  translatedText: string;
  detectedLanguage?: string;
} {
  const entry = demoTranslatedBodies[message.id];
  if (!entry) return { translatedText: message.textBody || message.snippet };
  return {
    translatedText: targetLocale.toLowerCase().startsWith("zh") ? entry.zh : entry.en,
    detectedLanguage: entry.detectedLanguage,
  };
}

export const demoStats: Stats = { accounts: 2, messages: 11, unread: 3 };
