import { createHash } from "node:crypto";
import { createWriteStream } from "node:fs";
import fs from "node:fs/promises";
import path from "node:path";
import { finished } from "node:stream/promises";
import type { UpdateManifestSignatureInput } from "./update-trust.mjs";

const stableVersionPattern = /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/;
const githubOwnerPattern = /^[A-Za-z0-9](?:[A-Za-z0-9-]{0,38})$/;
const githubRepositoryPattern = /^[A-Za-z0-9_.-]+$/;
const sha512Base64Pattern = /^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/;
const manifestMaximumBytes = 16 * 1024;

export type GitHubUpdateSource = {
  owner: string;
  repo: string;
};

export type GitHubZipUpdate = {
  source: GitHubUpdateSource;
  version: string;
  tag: string;
  archiveName: string;
  archiveUrl: string;
  archiveSize: number;
  archiveSha512: string;
  installerName: string;
};

export type UpdateDownloadProgress = {
  transferred: number;
  total: number;
  percent: number;
};

export class GitHubZipUpdateError extends Error {
  constructor(
    readonly code: string,
    message: string,
  ) {
    super(message);
    this.name = "GitHubZipUpdateError";
  }
}

type GitHubReleaseAsset = {
  name: string;
  size: number;
};

type GitHubRelease = {
  tag_name: string;
  draft: boolean;
  prerelease: boolean;
  assets: GitHubReleaseAsset[];
};

type UpdateManifest = {
  schemaVersion: 1;
  version: string;
  archive: {
    name: string;
    size: number;
    sha512: string;
  };
  installer: string;
  signature: UpdateManifestSignatureInput["signature"];
};

type FetchImplementation = typeof globalThis.fetch;

function isStableVersion(value: string): boolean {
  return stableVersionPattern.test(value);
}

function stableVersionParts(value: string): [number, number, number] | undefined {
  const match = stableVersionPattern.exec(value);
  if (!match) return undefined;
  const major = Number(match[1]);
  const minor = Number(match[2]);
  const patch = Number(match[3]);
  return Number.isSafeInteger(major) && Number.isSafeInteger(minor) && Number.isSafeInteger(patch)
    ? [major, minor, patch]
    : undefined;
}

export function compareStableVersions(left: string, right: string): number {
  const leftParts = stableVersionParts(left);
  const rightParts = stableVersionParts(right);
  if (!leftParts || !rightParts) throw new Error("Only stable x.y.z versions can be compared.");
  for (let index = 0; index < leftParts.length; index += 1) {
    const difference = (leftParts[index] ?? 0) - (rightParts[index] ?? 0);
    if (difference !== 0) return difference;
  }
  return 0;
}

export function githubZipUpdateAssetNames(version: string): {
  archiveName: string;
  manifestName: string;
  installerName: string;
} {
  if (!isStableVersion(version)) throw new Error("GitHub ZIP update assets require a stable x.y.z version.");
  return {
    archiveName: `nami-mail-update-${version}-win-x64.zip`,
    manifestName: `nami-mail-update-${version}-win-x64.json`,
    installerName: `Nami Mail Setup ${version}.exe`,
  };
}

function unquoteYamlScalar(value: string): string | undefined {
  const trimmed = value.trim();
  if (!trimmed) return undefined;
  if (trimmed.startsWith('"') && trimmed.endsWith('"') && trimmed.length >= 2) {
    try {
      const parsed = JSON.parse(trimmed);
      return typeof parsed === "string" ? parsed : undefined;
    } catch {
      return undefined;
    }
  }
  if (trimmed.startsWith("'") && trimmed.endsWith("'") && trimmed.length >= 2) {
    const raw = trimmed.slice(1, -1);
    return raw.replaceAll("''", "'");
  }
  return /^[^#\r\n]+$/.test(trimmed) ? trimmed.trim() : undefined;
}

/**
 * `app-update.yml` is generated by electron-builder. The desktop process only
 * needs its three scalar GitHub fields, so this parser deliberately rejects a
 * source that is not an explicit, simple GitHub provider configuration.
 */
export function parseGitHubUpdateSource(updateConfig: string): GitHubUpdateSource | undefined {
  const values = new Map<string, string>();
  for (const line of updateConfig.replace(/^\uFEFF/, "").split(/\r?\n/)) {
    if (/^\s/.test(line) || !line.trim() || line.trimStart().startsWith("#")) continue;
    const match = /^([A-Za-z][A-Za-z0-9_-]*):\s*(.*?)\s*$/.exec(line);
    if (!match) continue;
    const key = match[1] ?? "";
    const value = unquoteYamlScalar(match[2] ?? "");
    if (value !== undefined) values.set(key, value);
  }
  if (values.get("provider") !== "github") return undefined;
  const owner = values.get("owner");
  const repo = values.get("repo");
  if (!owner || !repo || !githubOwnerPattern.test(owner) || !githubRepositoryPattern.test(repo)) return undefined;
  return { owner, repo };
}

export async function loadGitHubUpdateSource(updateConfigPath: string): Promise<GitHubUpdateSource | undefined> {
  try {
    return parseGitHubUpdateSource(await fs.readFile(updateConfigPath, "utf8"));
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return undefined;
    throw error;
  }
}

function githubApiUrl(source: GitHubUpdateSource): string {
  return `https://api.github.com/repos/${encodeURIComponent(source.owner)}/${encodeURIComponent(source.repo)}/releases/latest`;
}

export function githubReleaseAssetUrl(source: GitHubUpdateSource, tag: string, assetName: string): string {
  return [
    "https://github.com",
    encodeURIComponent(source.owner),
    encodeURIComponent(source.repo),
    "releases",
    "download",
    encodeURIComponent(tag),
    encodeURIComponent(assetName),
  ].join("/");
}

function githubHeaders(): Record<string, string> {
  return {
    Accept: "application/vnd.github+json",
    "User-Agent": "Nami-Mail-desktop-updater",
    "X-GitHub-Api-Version": "2022-11-28",
  };
}

async function readResponseText(response: Response, maximumBytes = manifestMaximumBytes): Promise<string> {
  const text = await response.text();
  if (Buffer.byteLength(text, "utf8") > maximumBytes) {
    throw new GitHubZipUpdateError("UPDATE_MANIFEST_TOO_LARGE", "GitHub update metadata exceeds the allowed size.");
  }
  return text;
}

async function githubResponseError(response: Response, fallbackCode: string): Promise<GitHubZipUpdateError> {
  const rateLimited = response.status === 403 && response.headers.get("x-ratelimit-remaining") === "0";
  const code = rateLimited ? "GITHUB_RATE_LIMIT" : response.status === 404 ? "GITHUB_NOT_FOUND" : fallbackCode;
  let detail = "";
  try {
    detail = (await readResponseText(response, 2_000)).replaceAll(/\s+/g, " ").trim();
  } catch {
    // Preserve the HTTP category even when GitHub closes a response body early.
  }
  return new GitHubZipUpdateError(code, `GitHub update request returned HTTP ${response.status}.${detail ? ` ${detail.slice(0, 300)}` : ""}`);
}

function record(value: unknown): Record<string, unknown> | undefined {
  return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : undefined;
}

function parseRelease(value: unknown): GitHubRelease {
  const release = record(value);
  if (!release || typeof release.tag_name !== "string" || typeof release.draft !== "boolean" || typeof release.prerelease !== "boolean" || !Array.isArray(release.assets)) {
    throw new GitHubZipUpdateError("GITHUB_RELEASE_INVALID", "GitHub returned malformed update release metadata.");
  }
  const assets = release.assets.map((asset) => {
    const candidate = record(asset);
    const size = candidate?.size;
    if (!candidate || typeof candidate.name !== "string" || typeof size !== "number" || !Number.isSafeInteger(size) || size < 1) {
      throw new GitHubZipUpdateError("GITHUB_RELEASE_INVALID", "GitHub update release contains an invalid asset descriptor.");
    }
    return { name: candidate.name, size };
  });
  return { tag_name: release.tag_name, draft: release.draft, prerelease: release.prerelease, assets };
}

function parseManifest(value: unknown, version: string, expectedArchiveName: string, expectedInstallerName: string): UpdateManifest {
  const manifest = record(value);
  const archive = record(manifest?.archive);
  const signature = manifest?.signature === undefined || manifest.signature === null
    ? null
    : record(manifest.signature);
  const archiveSize = archive?.size;
  if (
    !manifest
    || manifest.schemaVersion !== 1
    || manifest.version !== version
    || typeof manifest.installer !== "string"
    || !archive
    || typeof archive.name !== "string"
    || typeof archiveSize !== "number"
    || !Number.isSafeInteger(archiveSize)
    || archiveSize < 1
    || typeof archive.sha512 !== "string"
  ) {
    throw new GitHubZipUpdateError("UPDATE_MANIFEST_INVALID", "GitHub update metadata has an unsupported format.");
  }
  if (archive.name !== expectedArchiveName || manifest.installer !== expectedInstallerName) {
    throw new GitHubZipUpdateError("UPDATE_MANIFEST_INVALID", "GitHub update metadata does not follow Nami Mail's release asset rule.");
  }
  if (!sha512Base64Pattern.test(archive.sha512) || Buffer.from(archive.sha512, "base64").byteLength !== 64) {
    throw new GitHubZipUpdateError("UPDATE_MANIFEST_INVALID", "GitHub update metadata does not contain a valid SHA-512 digest.");
  }
  if (signature && (signature.algorithm !== "ed25519" || typeof signature.value !== "string" || !sha512Base64Pattern.test(signature.value))) {
    throw new GitHubZipUpdateError("UPDATE_MANIFEST_INVALID", "GitHub update metadata contains an invalid release signature.");
  }
  if (manifest.signature !== undefined && manifest.signature !== null && !signature) {
    throw new GitHubZipUpdateError("UPDATE_MANIFEST_INVALID", "GitHub update metadata contains an invalid release signature.");
  }
  return {
    schemaVersion: 1,
    version,
    archive: { name: archive.name, size: archiveSize, sha512: archive.sha512 },
    installer: manifest.installer,
    signature: signature
      ? { algorithm: "ed25519", value: signature.value as string }
      : null,
  };
}

export async function discoverGitHubZipUpdate(options: {
  source: GitHubUpdateSource;
  currentVersion: string;
  fetchImpl?: FetchImplementation;
  verifyManifestSignature?: (input: UpdateManifestSignatureInput) => boolean;
}): Promise<GitHubZipUpdate | undefined> {
  const fetchImpl = options.fetchImpl ?? globalThis.fetch;
  if (typeof fetchImpl !== "function") throw new GitHubZipUpdateError("UPDATE_FETCH_UNAVAILABLE", "The desktop runtime does not provide a network fetch implementation.");
  if (!isStableVersion(options.currentVersion)) throw new GitHubZipUpdateError("UPDATE_VERSION_INVALID", "The installed app version is not a stable x.y.z release version.");

  const releaseResponse = await fetchImpl(githubApiUrl(options.source), { headers: githubHeaders(), redirect: "error" });
  if (!releaseResponse.ok) throw await githubResponseError(releaseResponse, "GITHUB_RELEASE_REQUEST_FAILED");
  const release = parseRelease(await releaseResponse.json());
  if (release.draft || release.prerelease || !release.tag_name.startsWith("v")) {
    throw new GitHubZipUpdateError("GITHUB_RELEASE_INVALID", "GitHub has no published stable Nami Mail update release.");
  }
  const version = release.tag_name.slice(1);
  if (!isStableVersion(version) || compareStableVersions(version, options.currentVersion) <= 0) return undefined;

  const { archiveName, manifestName, installerName } = githubZipUpdateAssetNames(version);
  const archiveAsset = release.assets.find((asset) => asset.name === archiveName);
  const manifestAsset = release.assets.find((asset) => asset.name === manifestName);
  if (!archiveAsset || !manifestAsset) {
    throw new GitHubZipUpdateError("UPDATE_ASSET_MISSING", "GitHub Release is missing the required Nami Mail ZIP update assets.");
  }

  const manifestResponse = await fetchImpl(githubReleaseAssetUrl(options.source, release.tag_name, manifestName), {
    headers: { Accept: "application/json", "User-Agent": "Nami-Mail-desktop-updater" },
    redirect: "follow",
  });
  if (!manifestResponse.ok) throw await githubResponseError(manifestResponse, "UPDATE_MANIFEST_REQUEST_FAILED");
  const manifestText = await readResponseText(manifestResponse);
  let manifestRaw: unknown;
  try {
    manifestRaw = JSON.parse(manifestText);
  } catch {
    throw new GitHubZipUpdateError("UPDATE_MANIFEST_INVALID", "GitHub update metadata is not valid JSON.");
  }
  const manifest = parseManifest(manifestRaw, version, archiveName, installerName);
  if (archiveAsset.size !== manifest.archive.size) {
    throw new GitHubZipUpdateError("UPDATE_MANIFEST_INVALID", "GitHub update metadata and ZIP asset size do not match.");
  }
  if (manifestAsset.size !== Buffer.byteLength(manifestText, "utf8")) {
    throw new GitHubZipUpdateError("UPDATE_MANIFEST_INVALID", "GitHub update metadata asset size does not match its contents.");
  }
  const signatureInput: UpdateManifestSignatureInput = {
    version,
    archiveName: manifest.archive.name,
    archiveSize: manifest.archive.size,
    archiveSha512: manifest.archive.sha512,
    installerName: manifest.installer,
    signature: manifest.signature,
  };
  if (options.verifyManifestSignature && !options.verifyManifestSignature(signatureInput)) {
    throw new GitHubZipUpdateError("UPDATE_MANIFEST_SIGNATURE_INVALID", "GitHub update metadata is not signed by this Nami Mail release channel.");
  }
  return {
    source: options.source,
    version,
    tag: release.tag_name,
    archiveName,
    archiveUrl: githubReleaseAssetUrl(options.source, release.tag_name, archiveName),
    archiveSize: manifest.archive.size,
    archiveSha512: manifest.archive.sha512,
    installerName: manifest.installer,
  };
}

export function updateArchivePath(cacheDirectory: string, update: Pick<GitHubZipUpdate, "version" | "archiveName">): string {
  return path.join(cacheDirectory, update.version, update.archiveName);
}

async function sha512File(filePath: string): Promise<{ size: number; sha512: string }> {
  const hash = createHash("sha512");
  let size = 0;
  const file = await fs.open(filePath, "r");
  try {
    const buffer = Buffer.allocUnsafe(256 * 1024);
    let position = 0;
    while (true) {
      const { bytesRead } = await file.read(buffer, 0, buffer.length, position);
      if (!bytesRead) break;
      position += bytesRead;
      size += bytesRead;
      hash.update(buffer.subarray(0, bytesRead));
    }
  } finally {
    await file.close();
  }
  return { size, sha512: hash.digest("base64") };
}

export async function hasVerifiedCachedUpdate(cacheDirectory: string, update: GitHubZipUpdate): Promise<boolean> {
  const archivePath = updateArchivePath(cacheDirectory, update);
  try {
    const digest = await sha512File(archivePath);
    return digest.size === update.archiveSize && digest.sha512 === update.archiveSha512;
  } catch {
    return false;
  }
}

async function writeChunk(stream: ReturnType<typeof createWriteStream>, chunk: Uint8Array): Promise<void> {
  if (stream.write(chunk)) return;
  await new Promise<void>((resolve, reject) => {
    stream.once("drain", resolve);
    stream.once("error", reject);
  });
}

export async function downloadGitHubZipUpdate(options: {
  cacheDirectory: string;
  update: GitHubZipUpdate;
  onProgress?: (progress: UpdateDownloadProgress) => void;
  fetchImpl?: FetchImplementation;
}): Promise<string> {
  const fetchImpl = options.fetchImpl ?? globalThis.fetch;
  const archivePath = updateArchivePath(options.cacheDirectory, options.update);
  if (await hasVerifiedCachedUpdate(options.cacheDirectory, options.update)) {
    options.onProgress?.({ transferred: options.update.archiveSize, total: options.update.archiveSize, percent: 100 });
    return archivePath;
  }
  const parentDirectory = path.dirname(archivePath);
  const temporaryPath = `${archivePath}.part`;
  await fs.mkdir(parentDirectory, { recursive: true });
  await fs.rm(temporaryPath, { force: true });

  try {
    const response = await fetchImpl(options.update.archiveUrl, {
      headers: { Accept: "application/octet-stream", "User-Agent": "Nami-Mail-desktop-updater" },
      redirect: "follow",
    });
    if (!response.ok) throw await githubResponseError(response, "UPDATE_DOWNLOAD_FAILED");
    if (!response.body) throw new GitHubZipUpdateError("UPDATE_DOWNLOAD_FAILED", "GitHub returned an empty ZIP update response.");
    const contentLengthHeader = response.headers.get("content-length");
    const contentLength = contentLengthHeader === null ? Number.NaN : Number(contentLengthHeader);
    if (Number.isFinite(contentLength) && contentLength !== options.update.archiveSize) {
      throw new GitHubZipUpdateError("UPDATE_DOWNLOAD_FAILED", "GitHub ZIP update size does not match published metadata.");
    }

    const hash = createHash("sha512");
    let transferred = 0;
    const stream = createWriteStream(temporaryPath, { flags: "wx", mode: 0o600 });
    try {
      for await (const chunk of response.body) {
        const bytes = Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk);
        transferred += bytes.byteLength;
        if (transferred > options.update.archiveSize) {
          throw new GitHubZipUpdateError("UPDATE_DOWNLOAD_FAILED", "GitHub ZIP update exceeds the published size.");
        }
        hash.update(bytes);
        await writeChunk(stream, bytes);
        options.onProgress?.({
          transferred,
          total: options.update.archiveSize,
          percent: Math.max(0, Math.min(100, Math.round((transferred / options.update.archiveSize) * 100))),
        });
      }
      stream.end();
      await finished(stream);
    } catch (error) {
      stream.destroy();
      await finished(stream).catch(() => undefined);
      throw error;
    }
    if (transferred !== options.update.archiveSize || hash.digest("base64") !== options.update.archiveSha512) {
      throw new GitHubZipUpdateError("UPDATE_DOWNLOAD_FAILED", "Downloaded ZIP update failed its published integrity check.");
    }
    await fs.rm(archivePath, { force: true });
    await fs.rename(temporaryPath, archivePath);
    return archivePath;
  } catch (error) {
    await fs.rm(temporaryPath, { force: true }).catch(() => undefined);
    throw error;
  }
}

export async function removeCachedGitHubZipUpdate(cacheDirectory: string, update: Pick<GitHubZipUpdate, "version">): Promise<void> {
  const updateDirectory = path.join(cacheDirectory, update.version);
  const relative = path.relative(cacheDirectory, updateDirectory);
  if (!relative || relative.startsWith("..") || path.isAbsolute(relative)) return;
  await fs.rm(updateDirectory, { recursive: true, force: true });
}
