// Generated by scripts/build-locale-catalog.mjs. Do not edit manually.
export const defaultNativeLocale = "zh-CN" as const;

export const nativeLocaleCatalog = {
  "en-US": {
    "trayTooltip": "Nami Mail",
    "trayOpen": "Open Nami Mail",
    "trayQuit": "Quit Nami Mail",
    "trayFailureTitle": "Unable to minimize to tray",
    "trayFailureMessage": "Nami Mail could not create a system tray icon. The window will stay open. Restart Nami Mail and try again.",
    "closePromptTitle": "When closing the window",
    "closePromptMessage": "Should Nami Mail keep receiving new mail in the background after the window closes?",
    "closePromptDetail": "When minimized to the tray, Nami Mail continues syncing mail and can show notifications. You can change this later in Settings > Desktop.",
    "closePromptMinimize": "Minimize to tray",
    "closePromptQuit": "Quit Nami Mail",
    "closePromptCancel": "Cancel",
    "closePromptRemember": "Remember my choice",
    "closePreferenceFailureTitle": "Unable to save close preference",
    "closePreferenceFailureMessage": "This choice will still be used now, but Nami Mail will ask again the next time you close the window.",
    "notificationUnknownSender": "New sender",
    "notificationSingleTitle": "{sender} · Nami Mail",
    "notificationMultipleTitle": "Nami Mail · {count} new messages",
    "notificationMultipleBody": "Messages from {sender} and others have synced to Inbox",
    "startupFailureTitle": "Nami Mail could not start",
    "startupFailureMessage": "The local mail service could not start."
  },
  "zh-CN": {
    "trayTooltip": "Nami Mail",
    "trayOpen": "打开 Nami Mail",
    "trayQuit": "退出 Nami Mail",
    "trayFailureTitle": "无法最小化到托盘",
    "trayFailureMessage": "系统托盘图标创建失败，窗口将保持打开。请重新启动 Nami Mail 后再试。",
    "closePromptTitle": "关闭窗口时",
    "closePromptMessage": "关闭窗口后，Nami Mail 要继续在后台接收新邮件吗？",
    "closePromptDetail": "最小化到托盘后会继续同步邮件和发送通知。以后可在“设置 > 桌面应用”中更改。",
    "closePromptMinimize": "最小化到托盘",
    "closePromptQuit": "退出 Nami Mail",
    "closePromptCancel": "取消",
    "closePromptRemember": "记住我的选择",
    "closePreferenceFailureTitle": "无法保存关闭偏好",
    "closePreferenceFailureMessage": "本次选择仍会执行，但下次关闭窗口时会再次询问。",
    "notificationUnknownSender": "新联系人",
    "notificationSingleTitle": "{sender} · Nami Mail",
    "notificationMultipleTitle": "Nami Mail · {count} 封新邮件",
    "notificationMultipleBody": "{sender} 等邮件已同步到收件箱",
    "startupFailureTitle": "Nami Mail 无法启动",
    "startupFailureMessage": "本地服务启动失败。"
  }
} as const;

export type NativeSupportedLocale = keyof typeof nativeLocaleCatalog;
